
import "@css/aos.css";
import "@css/bootstrap.min.css";
import "@css/flaticon.min.css";
import "@css/fontawesome-5.14.0.min.css";
import "@css/magnific-popup.min.css";
import "@css/nice-select.min.css";
import "@css/slick.min.css";
import "@css/style.css";
import "./globals.css";
import ReduxProvider from "../components/custom/ReduxProvider";
export const metadata = {
  title: "Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
       <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />

      </head>

      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
